services:
  database:
    image: postgis/postgis:latest
    container_name: fuel_price_postgis
    env_file: .env.postgis
    ports:
      - "5432:5432" #TODO: remove this from prod so we don't forward this to the host unecessarily
    volumes:
      - ${PWD}/db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d # seed scripts go here
    networks:
      - postgis_network
    restart: unless-stopped

  migrations:
    build:
      context: .
      dockerfile: ./alembic/Dockerfile
    container_name: fuel_price_alembic_migrations
    depends_on:
      - database
    env_file: .env.migrations
    networks:
      - postgis_network

  etl:
    build:
      context: . # Set to root of repo
      dockerfile: ./etls/Dockerfile
    container_name: fuelprice_etl
    depends_on:
      - migrations
    volumes:
      - ./etl_scripts:/app/etl_scripts
    env_file: .env.etl
    networks:
      - postgis_network
    # restart: unless-stopped

networks:
  postgis_network:
    driver: bridge
