services:
  database:
    image: postgis/postgis:latest
    container_name: fuel_price_postgis
    env_file: .env.postgis
    ports:
      - "5432:5432" #TODO: remove this from prod so we don't forward this to the host unecessarily
    volumes:
      - ${PWD}/db_data:/var/lib/postgresql/data
    networks:
      - postgis_network
    restart: unless-stopped

  migrations:
    build:
      context: .
      dockerfile: ./alembic/Dockerfile
    container_name: fuel_price_alembic_migrations
    depends_on:
      - database
    env_file: .env.migrations
    networks:
      - postgis_network

  grafana:
    image: grafana/grafana
    container_name: fuel_price_grafana
    ports:
      - "3000:3000"
    #TODO: Maybe map this to host
    # volumes:
    # - ${PWD}/grafana_data:/var/lib/grafana
    #TODO: UPDATE THIS TO ENVIRONMENT VARIABLES
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - postgis_network

  etl:
    build:
      context: . # Set to root of repo
      dockerfile: ./etls/Dockerfile
    container_name: fuelprice_etl
    depends_on:
      - migrations
    volumes:
      - ./etl_scripts:/app/etl_scripts
    env_file: .env.etl
    networks:
      - postgis_network
    # restart: unless-stopped

networks:
  postgis_network:
    driver: bridge
